spring:
  profiles:
    active: local
  application:
    name: api-gateway
    description: "External api gateway"
  jackson:
    time-zone: "Asia/Seoul"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
      base-path: /actuator
      path-mapping:
        health: health
